In [71]:
import pandas as pd

In [72]:
df = pd.read_csv("../data/raw/customer_support_tickets.csv")

In [73]:
df.head()

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,"I'm having an issue with the {product_purchased}. Please assist.\n\nYour billing zip code is: 71701.\n\nWe appreciate that you have requested a website address.\n\nPlease double check your email address. I've tried troubleshooting steps mentioned in the user manual, but the issue persists.",Pending Customer Response,NaN,Critical,Social media,2023-06-01 12:15:36,NaN,NaN
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,"I'm having an issue with the {product_purchased}. Please assist.\n\nIf you need to change an existing product.\n\nI'm having an issue with the {product_purchased}. Please assist.\n\nIf The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.",Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,"I'm facing a problem with my {product_purchased}. The {product_purchased} is not turning on. It was working fine until yesterday, but now it doesn't respond.\n\n1.8.3 I really I'm using the original charger that came with my {product_purchased}, but it's not charging properly.",Closed,Case maybe show recently my computer follow.,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,"I'm having an issue with the {product_purchased}. Please assist.\n\nIf you have a problem you're interested in and I'd love to see this happen, please check out the Feedback. I've already contacted customer support multiple times, but the issue remains unresolved.",Closed,Try capital clearly never color toward story.,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the {product_purchased}. Please assist.\n\n\nNote: The seller is not responsible for any damages arising out of the delivery of the battleground game. Please have the game in good condition and shipped to you I've noticed a sudden decrease in battery life on my {product_purchased}. It used to last much longer.,Closed,West decision evidence bit.,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0

In [74]:
df.shape

(8469, 17)

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8469 entries, 0 to 8468
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Ticket ID                     8469 non-null   int64
 1   Customer Name                 8469 non-null   object
 2   Customer Email                8469 non-null   object
 3   Customer Age                  8469 non-null   int64
 4   Customer Gender               8469 non-null   object
 5   Product Purchased             8469 non-null   object
 6   Date of Purchase              8469 non-null   object
 7   Ticket Type                   8469 non-null   object
 8   Ticket Subject                8469 non-null   object
 9   Ticket Description            8469 non-null   object
 10  Ticket Status                 8469 non-null   object
 11  Resolution                    2769 non-null   object
 12  Ticket Priority               8469 non-null   object
 13  Ticket Channel                8469 non-null   object
 14  First Response Time           5650 non-null   object
 15  Time to Resolution            2769 non-null   object
 16  Customer Satisfaction Rating  2769 non-null   float64
dtypes: float64(1), int64(2), object(14)
memory usage: 1.1+ MB

In [76]:
df.isnull().sum()

Ticket ID                          0
Customer Name                      0
Customer Email                     0
Customer Age                       0
Customer Gender                    0
Product Purchased                  0
Date of Purchase                   0
Ticket Type                        0
Ticket Subject                     0
Ticket Description                 0
Ticket Status                      0
Resolution                      5700
Ticket Priority                    0
Ticket Channel                     0
First Response Time             2819
Time to Resolution              5700
Customer Satisfaction Rating    5700
dtype: int64

In [77]:
df["Ticket Type"].value_counts()

Ticket Type
Refund request          1752
Technical issue         1747
Cancellation request    1695
Product inquiry         1641
Billing inquiry         1634
Name: count, dtype: int64

In [78]:
df[["Ticket Type", "Ticket Subject", "Ticket Description"]].head(10)

,Ticket Type,Ticket Subject,Ticket Description
0,Technical issue,Product setup,"I'm having an issue with the {product_purchased}. Please assist.\n\nYour billing zip code is: 71701.\n\nWe appreciate that you have requested a website address.\n\nPlease double check your email address. I've tried troubleshooting steps mentioned in the user manual, but the issue persists."
1,Technical issue,Peripheral compatibility,"I'm having an issue with the {product_purchased}. Please assist.\n\nIf you need to change an existing product.\n\nI'm having an issue with the {product_purchased}. Please assist.\n\nIf The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly."
2,Technical issue,Network problem,"I'm facing a problem with my {product_purchased}. The {product_purchased} is not turning on. It was working fine until yesterday, but now it doesn't respond.\n\n1.8.3 I really I'm using the original charger that came with my {product_purchased}, but it's not charging properly."
3,Billing inquiry,Account access,"I'm having an issue with the {product_purchased}. Please assist.\n\nIf you have a problem you're interested in and I'd love to see this happen, please check out the Feedback. I've already contacted customer support multiple times, but the issue remains unresolved."
4,Billing inquiry,Data loss,I'm having an issue with the {product_purchased}. Please assist.\n\n\nNote: The seller is not responsible for any damages arising out of the delivery of the battleground game. Please have the game in good condition and shipped to you I've noticed a sudden decrease in battery life on my {product_purchased}. It used to last much longer.
5,Cancellation request,Payment issue,"I'm facing a problem with my {product_purchased}. The {product_purchased} is not turning on. It was working fine until yesterday, but now it doesn't respond. To remove the new {product_purch I've checked for any available software updates for my {product_purchased}, but there are none."
6,Product inquiry,Refund request,"I'm unable to access my {product_purchased} account. It keeps displaying an 'Invalid Credentials' error, even though I'm using the correct login information. How can I regain access to my account?\n\nSolution 1 I'm unable to find the option to perform the desired action in the {product_purchased}. Could you please guide me through the steps?"
7,Refund request,Battery life,"I'm having an issue with the {product_purchased}. Please assist. (Thanks) I will contact all my suppliers and confirm.\n\nPlease try and find out whether their inventory is currently stocked, or any other reason. I am I've performed a factory reset on my {product_purchased}, hoping it would resolve the problem, but it didn't help."
8,Technical issue,Installation support,"I'm having an issue with the {product_purchased}. Please assist. Thank you.\n\n{product_purchased} is not the exact type you might prefer, they use the exact same method for different uses. Please help I've recently updated the firmware of my {product_purchased}, and the issue started happening afterward. Could it be related to the update?"
9,Refund request,Payment issue,"My {product_purchased} is making strange noises and not functioning properly. I suspect there might be a hardware issue. Can you please help me with this?\n\n} If we can, please send a ""request"" to dav The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly."

In [79]:
pd.set_option("display.max_colwidth", None)

df[["Ticket Type", "Ticket Subject", "Ticket Description"]].sample(5, random_state=42)

,Ticket Type,Ticket Subject,Ticket Description
4830,Refund request,Product setup,"I'm having an issue with the {product_purchased}. Please assist. I'm using xda-developer for something different. If there are issues with the {product_purchased} it's likely you are not using the I've tried clearing the cache and data for the {product_purchased} app, but the issue persists."
7075,Product inquiry,Battery life,"I'm having trouble connecting my {product_purchased} to my home Wi-Fi network. It doesn't detect any networks, although other devices are connecting fine. What can be done to resolve this issue? I will refer to this issue I've checked for any available software updates for my {product_purchased}, but there are none."
4715,Billing inquiry,Refund request,I'm having an issue with the {product_purchased}. Please assist.\n\nPlease give credit to: @joeyclay I'm concerned about the security of my {product_purchased} and would like to ensure that my data is safe.
2022,Billing inquiry,Peripheral compatibility,I'm having an issue with the {product_purchased}. Please assist.\n\n4. Check and compare product pricing\n\nYou will see that prices are based on the current prices on your credit card. If you are a resident of I've noticed a peculiar error message popping up on my {product_purchased} screen. It says '{error_message}'. What does it mean?
676,Refund request,Peripheral compatibility,I'm having an issue with the {product_purchased}. Please assist.\n\nI would like my price to rise so that I can return it.\n\nPlease notify me if you do not want their refund.\n\nPlease do I've noticed a sudden decrease in battery life on my {product_purchased}. It used to last much longer.

In [80]:
df.groupby("Ticket Type")["Ticket Subject"].nunique()

Ticket Type
Billing inquiry         16
Cancellation request    16
Product inquiry         16
Refund request          16
Technical issue         16
Name: Ticket Subject, dtype: int64

In [81]:
df["Ticket Subject"].value_counts().head(20)

Ticket Subject
Refund request              576
Software bug                574
Product compatibility       567
Delivery problem            561
Hardware issue              547
Battery life                542
Network problem             539
Installation support        530
Product setup               529
Payment issue               526
Product recommendation      517
Account access              509
Peripheral compatibility    496
Data loss                   491
Cancellation request        487
Display issue               478
Name: count, dtype: int64

In [82]:
pd.crosstab(df["Ticket Subject"], df["Ticket Type"])

Ticket Type,Billing inquiry,Cancellation request,Product inquiry,Refund request,Technical issue
Ticket Subject,,,,,
Account access,103,92,107,108,99
Battery life,106,104,101,119,112
Cancellation request,82,103,85,109,108
Data loss,89,115,91,97,99
Delivery problem,115,114,109,107,116
Display issue,91,103,80,99,105
Hardware issue,100,109,106,129,103
Installation support,108,99,99,119,105
Network problem,95,102,113,107,122
Payment issue,107,113,91,104,111
Peripheral compatibility,94,102,93,106,101
Product compatibility,123,97,121,107,119
Product recommendation,95,98,111,106,107
Product setup,104,108,100,104,113
Refund request,100,126,122,119,109
Software bug,122,110,112,112,118

In [83]:
df[["Ticket Type", "Ticket Description"]].sample(10, random_state=42)

,Ticket Type,Ticket Description
4830,Refund request,"I'm having an issue with the {product_purchased}. Please assist. I'm using xda-developer for something different. If there are issues with the {product_purchased} it's likely you are not using the I've tried clearing the cache and data for the {product_purchased} app, but the issue persists."
7075,Product inquiry,"I'm having trouble connecting my {product_purchased} to my home Wi-Fi network. It doesn't detect any networks, although other devices are connecting fine. What can be done to resolve this issue? I will refer to this issue I've checked for any available software updates for my {product_purchased}, but there are none."
4715,Billing inquiry,I'm having an issue with the {product_purchased}. Please assist.\n\nPlease give credit to: @joeyclay I'm concerned about the security of my {product_purchased} and would like to ensure that my data is safe.
2022,Billing inquiry,I'm having an issue with the {product_purchased}. Please assist.\n\n4. Check and compare product pricing\n\nYou will see that prices are based on the current prices on your credit card. If you are a resident of I've noticed a peculiar error message popping up on my {product_purchased} screen. It says '{error_message}'. What does it mean?
676,Refund request,I'm having an issue with the {product_purchased}. Please assist.\n\nI would like my price to rise so that I can return it.\n\nPlease notify me if you do not want their refund.\n\nPlease do I've noticed a sudden decrease in battery life on my {product_purchased}. It used to last much longer.
2283,Refund request,I've encountered a data loss issue with my {product_purchased}. All the files and documents seem to have disappeared. Can you guide me on how to retrieve them?\n\n\nI cannot verify this information though. It doesn't look very I've noticed that the issue occurs consistently when I use a specific feature or application on my {product_purchased}.
5076,Product inquiry,I'm having an issue with the {product_purchased}. Please assist. I've noticed a peculiar error message popping up on my {product_purchased} screen. It says '{error_message}'. What does it mean?
2476,Refund request,I'm having an issue with the {product_purchased}. Please assist.\n\nIf you are having trouble with your package you need to contact customer service with the following:\n\nWebsite\n\nP.O. Box 300 I've noticed a sudden decrease in battery life on my {product_purchased}. It used to last much longer.
6847,Refund request,"I'm encountering a software bug in the {product_purchased}. Whenever I try to perform a specific action, the application crashes. Are there any updates or fixes available? Will my account get frozen in order to save money? Is my password I've checked for software updates, and my {product_purchased} is already running the latest version."
511,Product inquiry,"I'm having an issue with the {product_purchased}. Please assist.\n\nThanks, and thanks a lot, I've tried clearing the cache and data for the {product_purchased} app, but the issue persists."

In [84]:
df["Ticket Type"].value_counts(normalize=True)

Ticket Type
Refund request          0.206872
Technical issue         0.206282
Cancellation request    0.200142
Product inquiry         0.193765
Billing inquiry         0.192939
Name: proportion, dtype: float64

In [85]:
df["text"] = (
    df["Ticket Subject"].fillna("") + " " +
    df["Ticket Description"].fillna("")
)

df[["text", "Ticket Type"]].head()

,text,Ticket Type
0,"Product setup I'm having an issue with the {product_purchased}. Please assist.\n\nYour billing zip code is: 71701.\n\nWe appreciate that you have requested a website address.\n\nPlease double check your email address. I've tried troubleshooting steps mentioned in the user manual, but the issue persists.",Technical issue
1,"Peripheral compatibility I'm having an issue with the {product_purchased}. Please assist.\n\nIf you need to change an existing product.\n\nI'm having an issue with the {product_purchased}. Please assist.\n\nIf The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.",Technical issue
2,"Network problem I'm facing a problem with my {product_purchased}. The {product_purchased} is not turning on. It was working fine until yesterday, but now it doesn't respond.\n\n1.8.3 I really I'm using the original charger that came with my {product_purchased}, but it's not charging properly.",Technical issue
3,"Account access I'm having an issue with the {product_purchased}. Please assist.\n\nIf you have a problem you're interested in and I'd love to see this happen, please check out the Feedback. I've already contacted customer support multiple times, but the issue remains unresolved.",Billing inquiry
4,Data loss I'm having an issue with the {product_purchased}. Please assist.\n\n\nNote: The seller is not responsible for any damages arising out of the delivery of the battleground game. Please have the game in good condition and shipped to you I've noticed a sudden decrease in battery life on my {product_purchased}. It used to last much longer.,Billing inquiry

In [86]:
from sklearn.model_selection import train_test_split

X = df["text"]
y = df["Ticket Type"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 6775
Testing samples: 1694

In [87]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    lowercase=True,
    stop_words="english",
    ngram_range=(1, 2),
    max_features=10000
)

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

print("Training matrix:", X_train_tfidf.shape)
print("Testing matrix:", X_test_tfidf.shape)

Training matrix: (6775, 10000)
Testing matrix: (1694, 10000)

In [88]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

model.fit(X_train_tfidf, y_train)

print("Model training complete!")

Model training complete!

In [89]:
y_pred = model.predict(X_test_tfidf)

print(y_pred[:10])

['Cancellation request' 'Refund request' 'Cancellation request'
 'Billing inquiry' 'Cancellation request' 'Technical issue'
 'Cancellation request' 'Product inquiry' 'Billing inquiry'
 'Cancellation request']

In [90]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("Accuracy percentage:", round(accuracy * 100, 2), "%")

Accuracy: 0.21428571428571427
Accuracy percentage: 21.43 %

In [91]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

                      precision    recall  f1-score   support

     Billing inquiry       0.22      0.21      0.22       327
Cancellation request       0.22      0.20      0.21       339
     Product inquiry       0.23      0.21      0.22       328
      Refund request       0.20      0.22      0.21       351
     Technical issue       0.21      0.23      0.22       349

            accuracy                           0.21      1694
           macro avg       0.22      0.21      0.21      1694
        weighted avg       0.21      0.21      0.21      1694

In [92]:
from sklearn.metrics import confusion_matrix
import pandas as pd

cm = confusion_matrix(y_test, y_pred, labels=model.classes_)

cm_df = pd.DataFrame(
    cm,
    index=model.classes_,
    columns=model.classes_
)

cm_df

,Billing inquiry,Cancellation request,Product inquiry,Refund request,Technical issue
Billing inquiry,70,51,60,80,66
Cancellation request,68,67,57,80,67
Product inquiry,54,55,70,70,79
Refund request,69,66,61,77,78
Technical issue,61,68,62,79,79

In [93]:
print("Unique subjects by Ticket Type:")
print(df.groupby("Ticket Type")["Ticket Subject"].nunique())

print("\nUnique descriptions by Ticket Type:")
print(df.groupby("Ticket Type")["Ticket Description"].nunique())

print("\nTotal unique subjects:", df["Ticket Subject"].nunique())
print("Total unique descriptions:", df["Ticket Description"].nunique())

Unique subjects by Ticket Type:
Ticket Type
Billing inquiry         16
Cancellation request    16
Product inquiry         16
Refund request          16
Technical issue         16
Name: Ticket Subject, dtype: int64

Unique descriptions by Ticket Type:
Ticket Type
Billing inquiry         1592
Cancellation request    1640
Product inquiry         1600
Refund request          1688
Technical issue         1670
Name: Ticket Description, dtype: int64

Total unique subjects: 16
Total unique descriptions: 8077

In [94]:
feature_names = vectorizer.get_feature_names_out()

for class_name, coefficients in zip(model.classes_, model.coef_):
    top_indices = coefficients.argsort()[-15:][::-1]
    
    print("\n", class_name)
    print(", ".join(feature_names[top_indices]))

 Billing inquiry
connect, apps, compatibility unable, good, bug hardware, buy item, later, products ve, new, know, make, net, today, assist issue, simple

 Cancellation request
thank having, donation, purchased ve, small, newsletter, missing, assist new, advance, sent, file, month, total, extra, solution yes, 19

 Product inquiry
product_p, options, vendor, trying, bug ve, issue problem, shop, provide, make sure, turn, buy, 99, customers, import, issue don

 Refund request
order, gift, solution, patience, product_name, question, help, ordered, follow, assist page, phone, assist experiencing, specified, personal, product_purchasing

 Technical issue
provided, assist don, items, things, feeling, assist unable, product_product, return, assist message, recommendation product_purchased, crash, patient, thanks issue, account step, don make

In [95]:
import re

def clean_text(text):
    text = str(text).lower()
    
    # Remove placeholders such as {product_purchased}
    text = re.sub(r"\{[^}]+\}", " ", text)
    
    # Remove newline characters
    text = re.sub(r"\\n+", " ", text)
    
    # Keep only letters and spaces
    text = re.sub(r"[^a-z\s]", " ", text)
    
    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()
    
    return text

df["clean_text"] = df["text"].apply(clean_text)

df[["text", "clean_text"]].head()

,text,clean_text
0,"Product setup I'm having an issue with the {product_purchased}. Please assist.\n\nYour billing zip code is: 71701.\n\nWe appreciate that you have requested a website address.\n\nPlease double check your email address. I've tried troubleshooting steps mentioned in the user manual, but the issue persists.",product setup i m having an issue with the please assist your billing zip code is we appreciate that you have requested a website address please double check your email address i ve tried troubleshooting steps mentioned in the user manual but the issue persists
1,"Peripheral compatibility I'm having an issue with the {product_purchased}. Please assist.\n\nIf you need to change an existing product.\n\nI'm having an issue with the {product_purchased}. Please assist.\n\nIf The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.",peripheral compatibility i m having an issue with the please assist if you need to change an existing product i m having an issue with the please assist if the issue i m facing is intermittent sometimes it works fine but other times it acts up unexpectedly
2,"Network problem I'm facing a problem with my {product_purchased}. The {product_purchased} is not turning on. It was working fine until yesterday, but now it doesn't respond.\n\n1.8.3 I really I'm using the original charger that came with my {product_purchased}, but it's not charging properly.",network problem i m facing a problem with my the is not turning on it was working fine until yesterday but now it doesn t respond i really i m using the original charger that came with my but it s not charging properly
3,"Account access I'm having an issue with the {product_purchased}. Please assist.\n\nIf you have a problem you're interested in and I'd love to see this happen, please check out the Feedback. I've already contacted customer support multiple times, but the issue remains unresolved.",account access i m having an issue with the please assist if you have a problem you re interested in and i d love to see this happen please check out the feedback i ve already contacted customer support multiple times but the issue remains unresolved
4,Data loss I'm having an issue with the {product_purchased}. Please assist.\n\n\nNote: The seller is not responsible for any damages arising out of the delivery of the battleground game. Please have the game in good condition and shipped to you I've noticed a sudden decrease in battery life on my {product_purchased}. It used to last much longer.,data loss i m having an issue with the please assist note the seller is not responsible for any damages arising out of the delivery of the battleground game please have the game in good condition and shipped to you i ve noticed a sudden decrease in battery life on my it used to last much longer

In [96]:
X = df["clean_text"]
y = df["Ticket Type"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 6775
Testing samples: 1694

In [97]:
vectorizer_clean = TfidfVectorizer(
    lowercase=True,
    stop_words="english",
    ngram_range=(1, 2),
    max_features=20000,
    min_df=2
)

X_train_tfidf = vectorizer_clean.fit_transform(X_train)
X_test_tfidf = vectorizer_clean.transform(X_test)

print("Training matrix:", X_train_tfidf.shape)
print("Testing matrix:", X_test_tfidf.shape)

Training matrix: (6775, 7821)
Testing matrix: (1694, 7821)

In [98]:
model_clean = LogisticRegression(
    max_iter=1000,
    random_state=42
)

model_clean.fit(X_train_tfidf, y_train)

print("Cleaned model training complete!")

Cleaned model training complete!

In [99]:
y_pred_clean = model_clean.predict(X_test_tfidf)

print(y_pred_clean[:10])

['Cancellation request' 'Refund request' 'Cancellation request'
 'Billing inquiry' 'Cancellation request' 'Technical issue'
 'Cancellation request' 'Refund request' 'Billing inquiry'
 'Cancellation request']

In [100]:
from sklearn.metrics import accuracy_score

accuracy_clean = accuracy_score(y_test, y_pred_clean)

print("Cleaned model accuracy:", accuracy_clean)
print("Cleaned model accuracy percentage:", round(accuracy_clean * 100, 2), "%")

Cleaned model accuracy: 0.21251475796930341
Cleaned model accuracy percentage: 21.25 %

In [101]:
from sklearn.svm import LinearSVC

svm_model = LinearSVC(random_state=42)

svm_model.fit(X_train_tfidf, y_train)

y_pred_svm = svm_model.predict(X_test_tfidf)

print("SVM accuracy:", accuracy_score(y_test, y_pred_svm))
print("SVM accuracy percentage:", round(accuracy_score(y_test, y_pred_svm) * 100, 2), "%")

SVM accuracy: 0.2077922077922078
SVM accuracy percentage: 20.78 %

In [102]:
from sklearn.feature_extraction.text import CountVectorizer

word_vectorizer = CountVectorizer(
    stop_words="english",
    max_features=30
)

word_vectorizer.fit(X_train)

print("Most common words:")
print(word_vectorizer.get_feature_names_out())

Most common words:
['access' 'account' 'assist' 'bug' 'compatibility' 'data' 'device'
 'hardware' 'having' 'help' 'issue' 'need' 'network' 'noticed' 'persists'
 'problem' 'product' 'request' 'resolve' 'software' 'started' 'steps'
 'support' 'times' 'tried' 'unable' 'update' 'use' 'using' 've']

In [103]:
for class_name, coefficients in zip(svm_model.classes_, svm_model.coef_):
    top_indices = coefficients.argsort()[-15:][::-1]

    print("\n", class_name)
    print(", ".join(vectorizer.get_feature_names_out()[top_indices]))

 Billing inquiry
brand ve, assist like, billing ve, 99 99, delivery problem, presented, product experiencing, 2017 10, product error, product 99, information products, constitute license, assist hope, chromebook ll, column preordered

 Cancellation request
code 0020, premium, firewall, recover data, brought, additional questions, asked refund, order fulfilled, 24 2015, product link, download issue, making strange, contact twitter, 24 hours, internationally

 Product inquiry
containing, contact verify, price possible, product_purchased_value, number customer, company know, friend, probably won, code console, connected power, message says, contact available, connection user, password account, documentation

 Refund request
contact credit, ll send, questions leave, address ve, fix problem, company tick, product experience, derek, recent issue, contact unable, page need, causing screen, connected need, buy products, 49 mobile

 Technical issue
closely authorities, com type, cause, confirm right, assist 22, clear offer, purchased using, prime, 12 17, contact info, recommend, handle, depending, list new, help going

In [104]:
import re

def clean_text(text):
    text = str(text).lower()

    # Remove template placeholders
    text = re.sub(r'\{[^}]+\}', ' ', text)

    # Remove numbers
    text = re.sub(r'\b\d+\b', ' ', text)

    # Remove URLs and email-like text
    text = re.sub(r'https?://\S+|www\.\S+', ' ', text)
    text = re.sub(r'\S+@\S+', ' ', text)

    # Keep only letters and spaces
    text = re.sub(r'[^a-z\s]', ' ', text)

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

df["clean_text"] = df["text"].apply(clean_text)

df[["text", "clean_text", "Ticket Type"]].head(10)

,text,clean_text,Ticket Type
0,"Product setup I'm having an issue with the {product_purchased}. Please assist.\n\nYour billing zip code is: 71701.\n\nWe appreciate that you have requested a website address.\n\nPlease double check your email address. I've tried troubleshooting steps mentioned in the user manual, but the issue persists.",product setup i m having an issue with the please assist your billing zip code is we appreciate that you have requested a website address please double check your email address i ve tried troubleshooting steps mentioned in the user manual but the issue persists,Technical issue
1,"Peripheral compatibility I'm having an issue with the {product_purchased}. Please assist.\n\nIf you need to change an existing product.\n\nI'm having an issue with the {product_purchased}. Please assist.\n\nIf The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.",peripheral compatibility i m having an issue with the please assist if you need to change an existing product i m having an issue with the please assist if the issue i m facing is intermittent sometimes it works fine but other times it acts up unexpectedly,Technical issue
2,"Network problem I'm facing a problem with my {product_purchased}. The {product_purchased} is not turning on. It was working fine until yesterday, but now it doesn't respond.\n\n1.8.3 I really I'm using the original charger that came with my {product_purchased}, but it's not charging properly.",network problem i m facing a problem with my the is not turning on it was working fine until yesterday but now it doesn t respond i really i m using the original charger that came with my but it s not charging properly,Technical issue
3,"Account access I'm having an issue with the {product_purchased}. Please assist.\n\nIf you have a problem you're interested in and I'd love to see this happen, please check out the Feedback. I've already contacted customer support multiple times, but the issue remains unresolved.",account access i m having an issue with the please assist if you have a problem you re interested in and i d love to see this happen please check out the feedback i ve already contacted customer support multiple times but the issue remains unresolved,Billing inquiry
4,Data loss I'm having an issue with the {product_purchased}. Please assist.\n\n\nNote: The seller is not responsible for any damages arising out of the delivery of the battleground game. Please have the game in good condition and shipped to you I've noticed a sudden decrease in battery life on my {product_purchased}. It used to last much longer.,data loss i m having an issue with the please assist note the seller is not responsible for any damages arising out of the delivery of the battleground game please have the game in good condition and shipped to you i ve noticed a sudden decrease in battery life on my it used to last much longer,Billing inquiry
5,"Payment issue I'm facing a problem with my {product_purchased}. The {product_purchased} is not turning on. It was working fine until yesterday, but now it doesn't respond. To remove the new {product_purch I've checked for any available software updates for my {product_purchased}, but there are none.",payment issue i m facing a problem with my the is not turning on it was working fine until yesterday but now it doesn t respond to remove the new but there are none,Cancellation request
6,"Refund request I'm unable to access my {product_purchased} account. It keeps displaying an 'Invalid Credentials' error, even though I'm using the correct login information. How can I regain access to my account?\n\nSolution 1 I'm unable to find the option to perform the desired action in the {product_purchased}. Could you please guide me through the steps?",refund request i m unable to access my account it keeps displaying an invalid credentials error even though i m using the correct login information how can i regain access to my account solution i m unable to find the option to perform the desired action in the could you please guide me through the steps,Product inquiry
7,"Battery life I'm having an issue with the {product_purchased}. Please assist. (Thanks) I will contact all my suppliers and confirm.\n\nPlease try and find out whether their inventory is currently stocked, or any other reason. I am I've performed a factory reset on my {product_purchased}, hoping it would resolve the problem, but it didn't help.",battery life i m having an issue with the please assist thanks i will contact all my suppliers and confirm please try and find out whether their inventory is currently stocked or any other reason i am i ve performed a factory reset on my hoping it would resolve the problem but it didn t help,Refund request
8,"Installation support I'm having an issue with the {product_purchased}. Please assist. Thank you.\n\n{product_purchased} is not the exact type you might prefer, they use the exact same method for different uses. Please help I've recently updated the firmware of my {product_purchased}, and the issue started happening afterward. Could it be related to the update?",installation support i m having an issue with the please assist thank you is not the exact type you might prefer they use the exact same method for different uses please help i ve recently updated the firmware of my and the issue started happening afterward could it be related to the update,Technical issue
9,"Payment issue My {product_purchased} is making strange noises and not functioning properly. I suspect there might be a hardware issue. Can you please help me with this?\n\n} If we can, please send a ""request"" to dav The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.",payment issue my is making strange noises and not functioning properly i suspect there might be a hardware issue can you please help me with this if we can please send a request to dav the issue i m facing is intermittent sometimes it works fine but other times it acts up unexpectedly,Refund request

In [105]:
X_clean = df["clean_text"]
y = df["Ticket Type"]

X_train_clean, X_test_clean, y_train_clean, y_test_clean = train_test_split(
    X_clean,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train_clean))
print("Testing samples:", len(X_test_clean))

Training samples: 6775
Testing samples: 1694

In [106]:
from sklearn.feature_extraction.text import TfidfVectorizer

clean_vectorizer = TfidfVectorizer(
    lowercase=True,
    stop_words="english",
    ngram_range=(1, 2),
    max_features=10000
)

X_train_clean_tfidf = clean_vectorizer.fit_transform(X_train_clean)
X_test_clean_tfidf = clean_vectorizer.transform(X_test_clean)

print("Training matrix:", X_train_clean_tfidf.shape)
print("Testing matrix:", X_test_clean_tfidf.shape)

Training matrix: (6775, 10000)
Testing matrix: (1694, 10000)

In [107]:
from sklearn.linear_model import LogisticRegression

clean_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

clean_model.fit(X_train_clean_tfidf, y_train_clean)

y_pred_clean = clean_model.predict(X_test_clean_tfidf)

print("Cleaned Logistic Regression accuracy:",
      accuracy_score(y_test_clean, y_pred_clean))

print(
    "Cleaned Logistic Regression accuracy percentage:",
    round(accuracy_score(y_test_clean, y_pred_clean) * 100, 2),
    "%"
)

Cleaned Logistic Regression accuracy: 0.21310507674144039
Cleaned Logistic Regression accuracy percentage: 21.31 %

In [108]:
description_check = (
    df.groupby("Ticket Description")["Ticket Type"]
    .nunique()
)

print("Total unique descriptions:", df["Ticket Description"].nunique())
print("Descriptions appearing with multiple ticket types:",
      (description_check > 1).sum())

print("\nMaximum number of different ticket types for one description:",
      description_check.max())

Total unique descriptions: 8077
Descriptions appearing with multiple ticket types: 42

Maximum number of different ticket types for one description: 5

In [109]:
from sklearn.dummy import DummyClassifier

dummy_model = DummyClassifier(
    strategy="most_frequent"
)

dummy_model.fit(X_train_tfidf, y_train)

y_pred_dummy = dummy_model.predict(X_test_tfidf)

dummy_accuracy = accuracy_score(y_test, y_pred_dummy)

print("Baseline accuracy:", dummy_accuracy)
print("Baseline accuracy percentage:",
      round(dummy_accuracy * 100, 2), "%")

Baseline accuracy: 0.20720188902007083
Baseline accuracy percentage: 20.72 %

In [110]:
subject_type_counts = pd.crosstab(
    df["Ticket Subject"],
    df["Ticket Type"]
)

print(subject_type_counts.head(20))

print("\nNumber of subjects:", len(subject_type_counts))
print("Subjects appearing in all 5 ticket types:",
      (subject_type_counts > 0).sum(axis=1).eq(5).sum())

Ticket Type               Billing inquiry  Cancellation request  \
Ticket Subject
Account access                        103                    92
Battery life                          106                   104
Cancellation request                   82                   103
Data loss                              89                   115
Delivery problem                      115                   114
Display issue                          91                   103
Hardware issue                        100                   109
Installation support                  108                    99
Network problem                        95                   102
Payment issue                         107                   113
Peripheral compatibility               94                   102
Product compatibility                 123                    97
Product recommendation                 95                    98
Product setup                         104                   108
Refund request                        100                   126
Software bug                          122                   110

Ticket Type               Product inquiry  Refund request  Technical issue
Ticket Subject
Account access                        107             108               99
Battery life                          101             119              112
Cancellation request                   85             109              108
Data loss                              91              97               99
Delivery problem                      109             107              116
Display issue                          80              99              105
Hardware issue                        106             129              103
Installation support                   99             119              105
Network problem                       113             107              122
Payment issue                          91             104              111
Peripheral compatibility               93             106              101
Product compatibility                 121             107              119
Product recommendation                111             106              107
Product setup                         100             104              113
Refund request                        122             119              109
Software bug                          112             112              118

Number of subjects: 16
Subjects appearing in all 5 ticket types: 16

In [111]:
feature_names = vectorizer.get_feature_names_out()

for class_name, coefficients in zip(model.classes_, model.coef_):
    top_indices = coefficients.argsort()[-20:][::-1]

    print("\n", class_name)
    print(", ".join(feature_names[top_indices]))

 Billing inquiry
connect, apps, compatibility unable, good, bug hardware, buy item, later, products ve, new, know, make, net, today, assist issue, simple, server, requested, assist issues, database, day

 Cancellation request
thank having, donation, purchased ve, small, newsletter, missing, assist new, advance, sent, file, month, total, extra, solution yes, 19, issue contact, deal, work ve, set, nice

 Product inquiry
product_p, options, vendor, trying, bug ve, issue problem, shop, provide, make sure, turn, buy, 99, customers, import, issue don, place, 40, assist trying, lot, turned

 Refund request
order, gift, solution, patience, product_name, question, help, ordered, follow, assist page, phone, assist experiencing, specified, personal, product_purchasing, https youtu, youtu, github, need help, param

 Technical issue
provided, assist don, items, things, feeling, assist unable, product_product, return, assist message, recommendation product_purchased, crash, patient, thanks issue, account step, don make, launch, said, history, long, pack

In [112]:
import re

def clean_text(text):
    text = str(text).lower()

    # Remove placeholders
    text = re.sub(r'\{[^}]+\}', ' ', text)

    # Remove numbers
    text = re.sub(r'\b\d+\b', ' ', text)

    # Remove punctuation and special characters
    text = re.sub(r'[^a-z\s]', ' ', text)

    # Remove common generic support words
    stop_words = {
        "i", "im", "ive", "please", "assist", "help",
        "issue", "problem", "having", "need", "want",
        "know", "just", "really", "like", "thanks",
        "thank", "support", "customer", "product",
        "purchased", "purchase", "using", "use",
        "tried", "trying", "noticed", "currently",
        "something", "anything", "would", "could",
        "also", "get", "got", "one", "make", "made"
    }

    words = text.split()

    words = [word for word in words if word not in stop_words]

    return " ".join(words)


df["clean_text"] = df["text"].apply(clean_text)

df[["text", "clean_text", "Ticket Type"]].head()

,text,clean_text,Ticket Type
0,"Product setup I'm having an issue with the {product_purchased}. Please assist.\n\nYour billing zip code is: 71701.\n\nWe appreciate that you have requested a website address.\n\nPlease double check your email address. I've tried troubleshooting steps mentioned in the user manual, but the issue persists.",setup m an with the your billing zip code is we appreciate that you have requested a website address double check your email address ve troubleshooting steps mentioned in the user manual but the persists,Technical issue
1,"Peripheral compatibility I'm having an issue with the {product_purchased}. Please assist.\n\nIf you need to change an existing product.\n\nI'm having an issue with the {product_purchased}. Please assist.\n\nIf The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.",peripheral compatibility m an with the if you to change an existing m an with the if the m facing is intermittent sometimes it works fine but other times it acts up unexpectedly,Technical issue
2,"Network problem I'm facing a problem with my {product_purchased}. The {product_purchased} is not turning on. It was working fine until yesterday, but now it doesn't respond.\n\n1.8.3 I really I'm using the original charger that came with my {product_purchased}, but it's not charging properly.",network m facing a with my the is not turning on it was working fine until yesterday but now it doesn t respond m the original charger that came with my but it s not charging properly,Technical issue
3,"Account access I'm having an issue with the {product_purchased}. Please assist.\n\nIf you have a problem you're interested in and I'd love to see this happen, please check out the Feedback. I've already contacted customer support multiple times, but the issue remains unresolved.",account access m an with the if you have a you re interested in and d love to see this happen check out the feedback ve already contacted multiple times but the remains unresolved,Billing inquiry
4,Data loss I'm having an issue with the {product_purchased}. Please assist.\n\n\nNote: The seller is not responsible for any damages arising out of the delivery of the battleground game. Please have the game in good condition and shipped to you I've noticed a sudden decrease in battery life on my {product_purchased}. It used to last much longer.,data loss m an with the note the seller is not responsible for any damages arising out of the delivery of the battleground game have the game in good condition and shipped to you ve a sudden decrease in battery life on my it used to last much longer,Billing inquiry

In [113]:
df["clean_text"].head(10)

0                                                                               setup m an with the your billing zip code is we appreciate that you have requested a website address double check your email address ve troubleshooting steps mentioned in the user manual but the persists
1                                                                                                         peripheral compatibility m an with the if you to change an existing m an with the if the m facing is intermittent sometimes it works fine but other times it acts up unexpectedly
2                                                                                                   network m facing a with my the is not turning on it was working fine until yesterday but now it doesn t respond m the original charger that came with my but it s not charging properly
3                                                                                                       account access m an with the if you have a you re interested in and d love to see this happen check out the feedback ve already contacted multiple times but the remains unresolved
4                                 data loss m an with the note the seller is not responsible for any damages arising out of the delivery of the battleground game have the game in good condition and shipped to you ve a sudden decrease in battery life on my it used to last much longer
5                                                                                                                                      payment m facing a with my the is not turning on it was working fine until yesterday but now it doesn t respond to remove the new but there are none
6    refund request m unable to access my account it keeps displaying an invalid credentials error even though m the correct login information how can regain access to my account solution m unable to find the option to perform the desired action in the you guide me through the steps
7                                                                    battery life m an with the will contact all my suppliers and confirm try and find out whether their inventory is stocked or any other reason am ve performed a factory reset on my hoping it resolve the but it didn t
8                                                                installation m an with the you is not the exact type you might prefer they the exact same method for different uses ve recently updated the firmware of my and the started happening afterward it be related to the update
9                                      payment my is making strange noises and not functioning properly suspect there might be a hardware can you me with this if we can send a request to dav the m facing is intermittent sometimes it works fine but other times it acts up unexpectedly
Name: clean_text, dtype: object

In [114]:
import re

def clean_text(text):
    text = str(text).lower()

    # Remove placeholders like {product_purchased}
    text = re.sub(r'\{[^}]+\}', ' ', text)

    # Handle common contractions before removing punctuation
    text = re.sub(r"\b i'm\b", " i am", text)
    text = re.sub(r"\b i've\b", " i have", text)
    text = re.sub(r"\b i'll\b", " i will", text)
    text = re.sub(r"\b i'd\b", " i would", text)
    text = re.sub(r"\b can't\b", " cannot", text)
    text = re.sub(r"\b won't\b", " will not", text)
    text = re.sub(r"\b doesn't\b", " does not", text)
    text = re.sub(r"\b isn't\b", " is not", text)
    text = re.sub(r"\b wasn't\b", " was not", text)
    text = re.sub(r"\b it's\b", " it is", text)

    # Remove numbers
    text = re.sub(r'\b\d+\b', ' ', text)

    # Keep only letters
    text = re.sub(r'[^a-z\s]', ' ', text)

    # Remove generic support/template words
    custom_stop_words = {
        "please",
        "assist",
        "help",
        "issue",
        "problem",
        "having",
        "need",
        "want",
        "really",
        "just",
        "thanks",
        "thank",
        "support",
        "customer",
        "purchased",
        "purchase",
        "using",
        "use",
        "tried",
        "trying",
        "noticed",
        "currently",
        "something",
        "anything",
        "would",
        "could"
    }

    words = text.split()

    words = [
        word for word in words
        if word not in custom_stop_words
    ]

    return " ".join(words)


df["clean_text"] = df["text"].apply(clean_text)

df[["text", "clean_text", "Ticket Type"]].head(10)

,text,clean_text,Ticket Type
0,"Product setup I'm having an issue with the {product_purchased}. Please assist.\n\nYour billing zip code is: 71701.\n\nWe appreciate that you have requested a website address.\n\nPlease double check your email address. I've tried troubleshooting steps mentioned in the user manual, but the issue persists.",product setup i am an with the your billing zip code is we appreciate that you have requested a website address double check your email address i ve troubleshooting steps mentioned in the user manual but the persists,Technical issue
1,"Peripheral compatibility I'm having an issue with the {product_purchased}. Please assist.\n\nIf you need to change an existing product.\n\nI'm having an issue with the {product_purchased}. Please assist.\n\nIf The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.",peripheral compatibility i am an with the if you to change an existing product i m an with the if the i am facing is intermittent sometimes it works fine but other times it acts up unexpectedly,Technical issue
2,"Network problem I'm facing a problem with my {product_purchased}. The {product_purchased} is not turning on. It was working fine until yesterday, but now it doesn't respond.\n\n1.8.3 I really I'm using the original charger that came with my {product_purchased}, but it's not charging properly.",network i am facing a with my the is not turning on it was working fine until yesterday but now it does not respond i i am the original charger that came with my but it is not charging properly,Technical issue
3,"Account access I'm having an issue with the {product_purchased}. Please assist.\n\nIf you have a problem you're interested in and I'd love to see this happen, please check out the Feedback. I've already contacted customer support multiple times, but the issue remains unresolved.",account access i am an with the if you have a you re interested in and i love to see this happen check out the feedback i ve already contacted multiple times but the remains unresolved,Billing inquiry
4,Data loss I'm having an issue with the {product_purchased}. Please assist.\n\n\nNote: The seller is not responsible for any damages arising out of the delivery of the battleground game. Please have the game in good condition and shipped to you I've noticed a sudden decrease in battery life on my {product_purchased}. It used to last much longer.,data loss i am an with the note the seller is not responsible for any damages arising out of the delivery of the battleground game have the game in good condition and shipped to you i have a sudden decrease in battery life on my it used to last much longer,Billing inquiry
5,"Payment issue I'm facing a problem with my {product_purchased}. The {product_purchased} is not turning on. It was working fine until yesterday, but now it doesn't respond. To remove the new {product_purch I've checked for any available software updates for my {product_purchased}, but there are none.",payment i am facing a with my the is not turning on it was working fine until yesterday but now it does not respond to remove the new but there are none,Cancellation request
6,"Refund request I'm unable to access my {product_purchased} account. It keeps displaying an 'Invalid Credentials' error, even though I'm using the correct login information. How can I regain access to my account?\n\nSolution 1 I'm unable to find the option to perform the desired action in the {product_purchased}. Could you please guide me through the steps?",refund request i am unable to access my account it keeps displaying an invalid credentials error even though i am the correct login information how can i regain access to my account solution i am unable to find the option to perform the desired action in the you guide me through the steps,Product inquiry
7,"Battery life I'm having an issue with the {product_purchased}. Please assist. (Thanks) I will contact all my suppliers and confirm.\n\nPlease try and find out whether their inventory is currently stocked, or any other reason. I am I've performed a factory reset on my {product_purchased}, hoping it would resolve the problem, but it didn't help.",battery life i am an with the i will contact all my suppliers and confirm try and find out whether their inventory is stocked or any other reason i am i have performed a factory reset on my hoping it resolve the but it didn t,Refund request
8,"Installation support I'm having an issue with the {product_purchased}. Please assist. Thank you.\n\n{product_purchased} is not the exact type you might prefer, they use the exact same method for different uses. Please help I've recently updated the firmware of my {product_purchased}, and the issue started happening afterward. Could it be related to the update?",installation i am an with the you is not the exact type you might prefer they the exact same method for different uses i have recently updated the firmware of my and the started happening afterward it be related to the update,Technical issue
9,"Payment issue My {product_purchased} is making strange noises and not functioning properly. I suspect there might be a hardware issue. Can you please help me with this?\n\n} If we can, please send a ""request"" to dav The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.",payment my is making strange noises and not functioning properly i suspect there might be a hardware can you me with this if we can send a request to dav the i am facing is intermittent sometimes it works fine but other times it acts up unexpectedly,Refund request

In [115]:
df["clean_text"].head(10)

0                                                                             product setup i am an with the your billing zip code is we appreciate that you have requested a website address double check your email address i ve troubleshooting steps mentioned in the user manual but the persists
1                                                                                                    peripheral compatibility i am an with the if you to change an existing product i m an with the if the i am facing is intermittent sometimes it works fine but other times it acts up unexpectedly
2                                                                                                    network i am facing a with my the is not turning on it was working fine until yesterday but now it does not respond i i am the original charger that came with my but it is not charging properly
3                                                                                                             account access i am an with the if you have a you re interested in and i love to see this happen check out the feedback i ve already contacted multiple times but the remains unresolved
4                                     data loss i am an with the note the seller is not responsible for any damages arising out of the delivery of the battleground game have the game in good condition and shipped to you i have a sudden decrease in battery life on my it used to last much longer
5                                                                                                                                             payment i am facing a with my the is not turning on it was working fine until yesterday but now it does not respond to remove the new but there are none
6    refund request i am unable to access my account it keeps displaying an invalid credentials error even though i am the correct login information how can i regain access to my account solution i am unable to find the option to perform the desired action in the you guide me through the steps
7                                                                    battery life i am an with the i will contact all my suppliers and confirm try and find out whether their inventory is stocked or any other reason i am i have performed a factory reset on my hoping it resolve the but it didn t
8                                                                    installation i am an with the you is not the exact type you might prefer they the exact same method for different uses i have recently updated the firmware of my and the started happening afterward it be related to the update
9                                            payment my is making strange noises and not functioning properly i suspect there might be a hardware can you me with this if we can send a request to dav the i am facing is intermittent sometimes it works fine but other times it acts up unexpectedly
Name: clean_text, dtype: object

In [116]:
import re

def clean_text(text):
    text = str(text).lower()

    # Remove placeholders
    text = re.sub(r'\{[^}]+\}', ' ', text)

    # Remove contractions instead of expanding them
    text = re.sub(r"\b(i'm|i've|i'll|i'd|it's|can't|won't|doesn't|isn't|wasn't|don't|didn't)\b", ' ', text)

    # Remove numbers
    text = re.sub(r'\b\d+\b', ' ', text)

    # Keep only letters
    text = re.sub(r'[^a-z\s]', ' ', text)

    # Remove generic support/template words
    custom_stop_words = {
        "please", "assist", "help", "issue", "problem",
        "having", "need", "want", "really", "just",
        "thanks", "thank", "support", "customer",
        "purchased", "purchase", "using", "use",
        "tried", "trying", "noticed", "currently",
        "something", "anything", "would", "could",
        "also", "get", "got", "one", "make", "made"
    }

    words = text.split()

    words = [
        word for word in words
        if word not in custom_stop_words
    ]

    return " ".join(words)


df["clean_text"] = df["text"].apply(clean_text)

df[["text", "clean_text", "Ticket Type"]].head(10)

,text,clean_text,Ticket Type
0,"Product setup I'm having an issue with the {product_purchased}. Please assist.\n\nYour billing zip code is: 71701.\n\nWe appreciate that you have requested a website address.\n\nPlease double check your email address. I've tried troubleshooting steps mentioned in the user manual, but the issue persists.",product setup an with the your billing zip code is we appreciate that you have requested a website address double check your email address troubleshooting steps mentioned in the user manual but the persists,Technical issue
1,"Peripheral compatibility I'm having an issue with the {product_purchased}. Please assist.\n\nIf you need to change an existing product.\n\nI'm having an issue with the {product_purchased}. Please assist.\n\nIf The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.",peripheral compatibility an with the if you to change an existing product an with the if the facing is intermittent sometimes it works fine but other times it acts up unexpectedly,Technical issue
2,"Network problem I'm facing a problem with my {product_purchased}. The {product_purchased} is not turning on. It was working fine until yesterday, but now it doesn't respond.\n\n1.8.3 I really I'm using the original charger that came with my {product_purchased}, but it's not charging properly.",network facing a with my the is not turning on it was working fine until yesterday but now it respond i the original charger that came with my but not charging properly,Technical issue
3,"Account access I'm having an issue with the {product_purchased}. Please assist.\n\nIf you have a problem you're interested in and I'd love to see this happen, please check out the Feedback. I've already contacted customer support multiple times, but the issue remains unresolved.",account access an with the if you have a you re interested in and love to see this happen check out the feedback already contacted multiple times but the remains unresolved,Billing inquiry
4,Data loss I'm having an issue with the {product_purchased}. Please assist.\n\n\nNote: The seller is not responsible for any damages arising out of the delivery of the battleground game. Please have the game in good condition and shipped to you I've noticed a sudden decrease in battery life on my {product_purchased}. It used to last much longer.,data loss an with the note the seller is not responsible for any damages arising out of the delivery of the battleground game have the game in good condition and shipped to you a sudden decrease in battery life on my it used to last much longer,Billing inquiry
5,"Payment issue I'm facing a problem with my {product_purchased}. The {product_purchased} is not turning on. It was working fine until yesterday, but now it doesn't respond. To remove the new {product_purch I've checked for any available software updates for my {product_purchased}, but there are none.",payment facing a with my the is not turning on it was working fine until yesterday but now it respond to remove the new but there are none,Cancellation request
6,"Refund request I'm unable to access my {product_purchased} account. It keeps displaying an 'Invalid Credentials' error, even though I'm using the correct login information. How can I regain access to my account?\n\nSolution 1 I'm unable to find the option to perform the desired action in the {product_purchased}. Could you please guide me through the steps?",refund request unable to access my account it keeps displaying an invalid credentials error even though the correct login information how can i regain access to my account solution unable to find the option to perform the desired action in the you guide me through the steps,Product inquiry
7,"Battery life I'm having an issue with the {product_purchased}. Please assist. (Thanks) I will contact all my suppliers and confirm.\n\nPlease try and find out whether their inventory is currently stocked, or any other reason. I am I've performed a factory reset on my {product_purchased}, hoping it would resolve the problem, but it didn't help.",battery life an with the i will contact all my suppliers and confirm try and find out whether their inventory is stocked or any other reason i am performed a factory reset on my hoping it resolve the but it,Refund request
8,"Installation support I'm having an issue with the {product_purchased}. Please assist. Thank you.\n\n{product_purchased} is not the exact type you might prefer, they use the exact same method for different uses. Please help I've recently updated the firmware of my {product_purchased}, and the issue started happening afterward. Could it be related to the update?",installation an with the you is not the exact type you might prefer they the exact same method for different uses recently updated the firmware of my and the started happening afterward it be related to the update,Technical issue
9,"Payment issue My {product_purchased} is making strange noises and not functioning properly. I suspect there might be a hardware issue. Can you please help me with this?\n\n} If we can, please send a ""request"" to dav The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.",payment my is making strange noises and not functioning properly i suspect there might be a hardware can you me with this if we can send a request to dav the facing is intermittent sometimes it works fine but other times it acts up unexpectedly,Refund request

In [117]:
df["clean_text"].head(10)

0                                                                        product setup an with the your billing zip code is we appreciate that you have requested a website address double check your email address troubleshooting steps mentioned in the user manual but the persists
1                                                                                                   peripheral compatibility an with the if you to change an existing product an with the if the facing is intermittent sometimes it works fine but other times it acts up unexpectedly
2                                                                                                              network facing a with my the is not turning on it was working fine until yesterday but now it respond i the original charger that came with my but not charging properly
3                                                                                                          account access an with the if you have a you re interested in and love to see this happen check out the feedback already contacted multiple times but the remains unresolved
4                                  data loss an with the note the seller is not responsible for any damages arising out of the delivery of the battleground game have the game in good condition and shipped to you a sudden decrease in battery life on my it used to last much longer
5                                                                                                                                            payment facing a with my the is not turning on it was working fine until yesterday but now it respond to remove the new but there are none
6    refund request unable to access my account it keeps displaying an invalid credentials error even though the correct login information how can i regain access to my account solution unable to find the option to perform the desired action in the you guide me through the steps
7                                                                        battery life an with the i will contact all my suppliers and confirm try and find out whether their inventory is stocked or any other reason i am performed a factory reset on my hoping it resolve the but it
8                                                                 installation an with the you is not the exact type you might prefer they the exact same method for different uses recently updated the firmware of my and the started happening afterward it be related to the update
9                                  payment my is making strange noises and not functioning properly i suspect there might be a hardware can you me with this if we can send a request to dav the facing is intermittent sometimes it works fine but other times it acts up unexpectedly
Name: clean_text, dtype: object

In [118]:
from sklearn.feature_extraction.text import TfidfVectorizer

clean_vectorizer = TfidfVectorizer(
    stop_words="english",
    ngram_range=(1, 2),
    max_features=10000
)

X_clean = clean_vectorizer.fit_transform(df["clean_text"])
y = df["Ticket Type"]

print("Cleaned TF-IDF matrix:", X_clean.shape)

Cleaned TF-IDF matrix: (8469, 10000)

In [119]:
from sklearn.model_selection import train_test_split

X_train_clean, X_test_clean, y_train_clean, y_test_clean = train_test_split(
    X_clean,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", X_train_clean.shape[0])
print("Testing samples:", X_test_clean.shape[0])

Training samples: 6775
Testing samples: 1694

In [120]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

clean_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

clean_model.fit(X_train_clean, y_train_clean)

y_pred_clean = clean_model.predict(X_test_clean)

clean_accuracy = accuracy_score(y_test_clean, y_pred_clean)

print("Cleaned Logistic Regression accuracy:", clean_accuracy)
print(
    "Cleaned Logistic Regression accuracy percentage:",
    round(clean_accuracy * 100, 2),
    "%"
)

Cleaned Logistic Regression accuracy: 0.21428571428571427
Cleaned Logistic Regression accuracy percentage: 21.43 %

In [121]:
import joblib
import os

os.makedirs("../models", exist_ok=True)

joblib.dump(model, "../models/logistic_model.pkl")
joblib.dump(vectorizer, "../models/tfidf_vectorizer.pkl")

print("Model and vectorizer saved successfully!")

Model and vectorizer saved successfully!

In [122]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Create improved TF-IDF features
improved_vectorizer = TfidfVectorizer(
    ngram_range=(1, 2),
    min_df=2,
    max_df=0.95,
    sublinear_tf=True
)

X_train_improved = improved_vectorizer.fit_transform(X_train)
X_test_improved = improved_vectorizer.transform(X_test)

print("Training features:", X_train_improved.shape)
print("Testing features:", X_test_improved.shape)

Training features: (6775, 14065)
Testing features: (1694, 14065)

In [123]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

improved_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

improved_model.fit(X_train_improved, y_train)

y_pred_improved = improved_model.predict(X_test_improved)

improved_accuracy = accuracy_score(y_test, y_pred_improved)

print("Improved Logistic Regression accuracy:", improved_accuracy)
print(
    "Improved Logistic Regression accuracy percentage:",
    round(improved_accuracy * 100, 2),
    "%"
)

Improved Logistic Regression accuracy: 0.2066115702479339
Improved Logistic Regression accuracy percentage: 20.66 %

In [124]:
from sklearn.svm import LinearSVC

improved_svm = LinearSVC(random_state=42)

improved_svm.fit(X_train_improved, y_train)

y_pred_svm_improved = improved_svm.predict(X_test_improved)

svm_improved_accuracy = accuracy_score(
    y_test,
    y_pred_svm_improved
)

print("Improved SVM accuracy:", svm_improved_accuracy)
print(
    "Improved SVM accuracy percentage:",
    round(svm_improved_accuracy * 100, 2),
    "%"
)

Improved SVM accuracy: 0.20956316410861867
Improved SVM accuracy percentage: 20.96 %

In [125]:
print("Ticket types:")
print(df["Ticket Type"].value_counts())

print("\nNumber of ticket types:", df["Ticket Type"].nunique())

Ticket types:
Ticket Type
Refund request          1752
Technical issue         1747
Cancellation request    1695
Product inquiry         1641
Billing inquiry         1634
Name: count, dtype: int64

Number of ticket types: 5

In [126]:
ambiguous = (
    df.groupby("Ticket Description")["Ticket Type"]
    .nunique()
    .sort_values(ascending=False)
)

print("Descriptions with more than one ticket type:")
print(ambiguous[ambiguous > 1].head(20))

print("\nTotal ambiguous descriptions:", (ambiguous > 1).sum())
print("Maximum labels for one description:", ambiguous.max())

Descriptions with more than one ticket type:
Ticket Description
I'm having an issue with the {product_purchased}. Please assist. I've performed a factory reset on my {product_purchased}, hoping it would resolve the problem, but it didn't help.                             5
I'm having an issue with the {product_purchased}. Please assist. I need assistance as soon as possible because it's affecting my work and productivity.                                                         5
I'm having an issue with the {product_purchased}. Please assist. I rely heavily on my {product_purchased} for my daily tasks, and this issue is hindering my productivity.                                      5
I'm having an issue with the {product_purchased}. Please assist. I'm concerned about the security of my {product_purchased} and would like to ensure that my data is safe.                                      5
I'm having an issue with the {product_purchased}. Please assist. I'm experiencing this issue on multiple devices of the same model, so it seems to be a widespread problem.                                     5
I'm having an issue with the {product_purchased}. Please assist. I'm not sure if this issue is specific to my device or if others have reported similar problems.                                               5
I'm having an issue with the {product_purchased}. Please assist. I'm unable to find the option to perform the desired action in the {product_purchased}. Could you please guide me through the steps?           5
I'm having an issue with the {product_purchased}. Please assist. This problem started occurring after the recent software update. I haven't made any other changes to the device.                               5
I'm having an issue with the {product_purchased}. Please assist. The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.                                        5
I'm having an issue with the {product_purchased}. Please assist. I've already contacted customer support multiple times, but the issue remains unresolved.                                                      5
I'm having an issue with the {product_purchased}. Please assist. I've tried using different cables, adapters, or peripherals with my {product_purchased}, but the issue persists.                               5
I'm having an issue with the {product_purchased}. Please assist. I've tried troubleshooting steps mentioned in the user manual, but the issue persists.                                                         5
I'm having an issue with the {product_purchased}. Please assist. I've tried different settings and configurations on my {product_purchased}, but the issue persists.                                            5
I'm having an issue with the {product_purchased}. Please assist. I've tried clearing the cache and data for the {product_purchased} app, but the issue persists.                                                5
I'm having an issue with the {product_purchased}. Please assist. I've recently updated the firmware of my {product_purchased}, and the issue started happening afterward. Could it be related to the update?    5
I'm having an issue with the {product_purchased}. Please assist. I've noticed a sudden decrease in battery life on my {product_purchased}. It used to last much longer.                                         5
I'm having an issue with the {product_purchased}. Please assist. I've noticed a peculiar error message popping up on my {product_purchased} screen. It says '{error_message}'. What does it mean?               5
I'm having an issue with the {product_purchased}. Please assist. I've checked for software updates, and my {product_purchased} is already running the latest version.                                           5
I'm having an issue with the {product_purchased}. Please assist. I'm using the original charger that came with my {product_purchased}, but it's not charging properly.                                          4
I'm having an issue with the {product_purchased}. Please assist. I'm worried that the issue might be hardware-related and might require repair or replacement.                                                  4
Name: Ticket Type, dtype: int64

Total ambiguous descriptions: 42
Maximum labels for one description: 5

In [127]:
ambiguous_descriptions = ambiguous[ambiguous > 1].index

ambiguous_rows = df[df["Ticket Description"].isin(ambiguous_descriptions)]

print("Total rows:", len(df))
print("Rows with ambiguous descriptions:", len(ambiguous_rows))
print("Percentage affected:", round(len(ambiguous_rows) / len(df) * 100, 2), "%")

Total rows: 8469
Rows with ambiguous descriptions: 429
Percentage affected: 5.07 %

In [128]:
ambiguous_rows[["Ticket Description", "Ticket Type"]].sort_values("Ticket Description").head(50)

,Ticket Description,Ticket Type
2661,I'm facing issues logging into my {product_purchased} account. It says my account is locked. What should I do to unlock it? I'm worried that the issue might be hardware-related and might require repair or replacement.,Cancellation request
6117,I'm facing issues logging into my {product_purchased} account. It says my account is locked. What should I do to unlock it? I'm worried that the issue might be hardware-related and might require repair or replacement.,Product inquiry
5296,I'm having an issue with the {product_purchased}. Please assist.\n\nI'm having an issue with the {product_purchased}. Please assist.\n\nI'm having an issue with the {product_purch I'm concerned about the security of my {product_purchased} and would like to ensure that my data is safe.,Billing inquiry
1104,I'm having an issue with the {product_purchased}. Please assist.\n\nI'm having an issue with the {product_purchased}. Please assist.\n\nI'm having an issue with the {product_purch I'm concerned about the security of my {product_purchased} and would like to ensure that my data is safe.,Product inquiry
7813,"I'm having an issue with the {product_purchased}. Please assist.\n\nI'm having an issue with the {product_purchased}. Please assist.\n\nI'm having an issue with the {product_purch I've followed online tutorials and community forums to troubleshoot the issue, but no luck so far.",Billing inquiry
8032,"I'm having an issue with the {product_purchased}. Please assist.\n\nI'm having an issue with the {product_purchased}. Please assist.\n\nI'm having an issue with the {product_purch I've followed online tutorials and community forums to troubleshoot the issue, but no luck so far.",Technical issue
4811,"I'm having an issue with the {product_purchased}. Please assist.\n\nI'm having an issue with the {product_purchased}. Please assist.\n\nI'm having an issue with the {product_purch I've followed online tutorials and community forums to troubleshoot the issue, but no luck so far.",Refund request
7501,I'm having an issue with the {product_purchased}. Please assist.\n\nThanks. I'm concerned about the security of my {product_purchased} and would like to ensure that my data is safe.,Cancellation request
5331,I'm having an issue with the {product_purchased}. Please assist.\n\nThanks. I'm concerned about the security of my {product_purchased} and would like to ensure that my data is safe.,Technical issue
2171,I'm having an issue with the {product_purchased}. Please assist. I need assistance as soon as possible because it's affecting my work and productivity.,Billing inquiry
6488,I'm having an issue with the {product_purchased}. Please assist. I need assistance as soon as possible because it's affecting my work and productivity.,Billing inquiry
7948,I'm having an issue with the {product_purchased}. Please assist. I need assistance as soon as possible because it's affecting my work and productivity.,Cancellation request
2855,I'm having an issue with the {product_purchased}. Please assist. I need assistance as soon as possible because it's affecting my work and productivity.,Technical issue
3668,I'm having an issue with the {product_purchased}. Please assist. I need assistance as soon as possible because it's affecting my work and productivity.,Refund request
1026,I'm having an issue with the {product_purchased}. Please assist. I need assistance as soon as possible because it's affecting my work and productivity.,Billing inquiry
105,I'm having an issue with the {product_purchased}. Please assist. I need assistance as soon as possible because it's affecting my work and productivity.,Product inquiry
6536,I'm having an issue with the {product_purchased}. Please assist. I need assistance as soon as possible because it's affecting my work and productivity.,Technical issue
2327,I'm having an issue with the {product_purchased}. Please assist. I need assistance as soon as possible because it's affecting my work and productivity.,Cancellation request
4751,I'm having an issue with the {product_purchased}. Please assist. I need assistance as soon as possible because it's affecting my work and productivity.,Cancellation request
5968,I'm having an issue with the {product_purchased}. Please assist. I need assistance as soon as possible because it's affecting my work and productivity.,Technical issue
5474,I'm having an issue with the {product_purchased}. Please assist. I need assistance as soon as possible because it's affecting my work and productivity.,Technical issue
5976,I'm having an issue with the {product_purchased}. Please assist. I need assistance as soon as possible because it's affecting my work and productivity.,Billing inquiry
2279,I'm having an issue with the {product_purchased}. Please assist. I need assistance as soon as possible because it's affecting my work and productivity.,Cancellation request
1544,I'm having an issue with the {product_purchased}. Please assist. I need assistance as soon as possible because it's affecting my work and productivity.,Technical issue
8177,I'm having an issue with the {product_purchased}. Please assist. I need assistance as soon as possible because it's affecting my work and productivity.,Technical issue
347,I'm having an issue with the {product_purchased}. Please assist. I need assistance as soon as possible because it's affecting my work and productivity.,Refund request
5116,I'm having an issue with the {product_purchased}. Please assist. I need assistance as soon as possible because it's affecting my work and productivity.,Technical issue
3849,I'm having an issue with the {product_purchased}. Please assist. I need assistance as soon as possible because it's affecting my work and productivity.,Cancellation request
6382,I'm having an issue with the {product_purchased}. Please assist. I need assistance as soon as possible because it's affecting my work and productivity.,Technical issue
7290,I'm having an issue with the {product_purchased}. Please assist. I need assistance as soon as possible because it's affecting my work and productivity.,Billing inquiry
7929,I'm having an issue with the {product_purchased}. Please assist. I need assistance as soon as possible because it's affecting my work and productivity.,Technical issue
8326,I'm having an issue with the {product_purchased}. Please assist. I need assistance as soon as possible because it's affecting my work and productivity.,Technical issue
4787,I'm having an issue with the {product_purchased}. Please assist. I need assistance as soon as possible because it's affecting my work and productivity.,Refund request
291,I'm having an issue with the {product_purchased}. Please assist. I need assistance as soon as possible because it's affecting my work and productivity.,Cancellation request
1932,"I'm having an issue with the {product_purchased}. Please assist. I rely heavily on my {product_purchased} for my daily tasks, and this issue is hindering my productivity.",Product inquiry
4227,"I'm having an issue with the {product_purchased}. Please assist. I rely heavily on my {product_purchased} for my daily tasks, and this issue is hindering my productivity.",Technical issue
5495,"I'm having an issue with the {product_purchased}. Please assist. I rely heavily on my {product_purchased} for my daily tasks, and this issue is hindering my productivity.",Product inquiry
4247,"I'm having an issue with the {product_purchased}. Please assist. I rely heavily on my {product_purchased} for my daily tasks, and this issue is hindering my productivity.",Billing inquiry
1161,"I'm having an issue with the {product_purchased}. Please assist. I rely heavily on my {product_purchased} for my daily tasks, and this issue is hindering my productivity.",Cancellation request
1977,"I'm having an issue with the {product_purchased}. Please assist. I rely heavily on my {product_purchased} for my daily tasks, and this issue is hindering my productivity.",Refund request
2301,"I'm having an issue with the {product_purchased}. Please assist. I rely heavily on my {product_purchased} for my daily tasks, and this issue is hindering my productivity.",Cancellation request
7602,"I'm having an issue with the {product_purchased}. Please assist. I rely heavily on my {product_purchased} for my daily tasks, and this issue is hindering my productivity.",Cancellation request
7323,"I'm having an issue with the {product_purchased}. Please assist. I rely heavily on my {product_purchased} for my daily tasks, and this issue is hindering my productivity.",Technical issue
4525,"I'm having an issue with the {product_purchased}. Please assist. I rely heavily on my {product_purchased} for my daily tasks, and this issue is hindering my productivity.",Refund request
4046,"I'm having an issue with the {product_purchased}. Please assist. I rely heavily on my {product_purchased} for my daily tasks, and this issue is hindering my productivity.",Refund request
7506,"I'm having an issue with the {product_purchased}. Please assist. I rely heavily on my {product_purchased} for my daily tasks, and this issue is hindering my productivity.",Technical issue
933,"I'm having an issue with the {product_purchased}. Please assist. I rely heavily on my {product_purchased} for my daily tasks, and this issue is hindering my productivity.",Technical issue
8040,"I'm having an issue with the {product_purchased}. Please assist. I rely heavily on my {product_purchased} for my daily tasks, and this issue is hindering my productivity.",Product inquiry
4718,"I'm having an issue with the {product_purchased}. Please assist. I rely heavily on my {product_purchased} for my daily tasks, and this issue is hindering my productivity.",Technical issue
456,I'm having an issue with the {product_purchased}. Please assist. I'm concerned about the security of my {product_purchased} and would like to ensure that my data is safe.,Refund request

In [129]:
# Remove descriptions that have multiple different ticket-type labels

clean_df = df[~df["Ticket Description"].isin(ambiguous_descriptions)].copy()

print("Original rows:", len(df))
print("Rows removed:", len(df) - len(clean_df))
print("Clean rows:", len(clean_df))

print("\nTicket types after cleaning:")
print(clean_df["Ticket Type"].value_counts())

Original rows: 8469
Rows removed: 429
Clean rows: 8040

Ticket types after cleaning:
Ticket Type
Refund request          1654
Technical issue         1644
Cancellation request    1608
Product inquiry         1572
Billing inquiry         1562
Name: count, dtype: int64

In [130]:
from sklearn.model_selection import train_test_split

X = clean_df["clean_text"]
y = clean_df["Ticket Type"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 6432
Testing samples: 1608

In [131]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    ngram_range=(1, 2),
    min_df=2,
    max_df=0.95,
    sublinear_tf=True
)

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

print("Training features:", X_train_tfidf.shape)
print("Testing features:", X_test_tfidf.shape)

Training features: (6432, 13208)
Testing features: (1608, 13208)

In [132]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

clean_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

clean_model.fit(X_train_tfidf, y_train)

y_pred_clean = clean_model.predict(X_test_tfidf)

clean_accuracy = accuracy_score(y_test, y_pred_clean)

print("Clean Logistic Regression accuracy:", clean_accuracy)
print(
    "Clean Logistic Regression accuracy percentage:",
    round(clean_accuracy * 100, 2),
    "%"
)

Clean Logistic Regression accuracy: 0.20024875621890548
Clean Logistic Regression accuracy percentage: 20.02 %

In [133]:
print("Actual test labels:")
print(y_test.value_counts())

print("\nPredicted test labels:")
print(pd.Series(y_pred_clean).value_counts())

print("\nFirst 20 predictions:")
for actual, predicted in zip(y_test.head(20), y_pred_clean[:20]):
    print("Actual:", actual, "| Predicted:", predicted)

Actual test labels:
Ticket Type
Refund request          331
Technical issue         329
Cancellation request    322
Product inquiry         314
Billing inquiry         312
Name: count, dtype: int64

Predicted test labels:
Refund request          373
Technical issue         346
Cancellation request    311
Product inquiry         296
Billing inquiry         282
Name: count, dtype: int64

First 20 predictions:
Actual: Technical issue | Predicted: Technical issue
Actual: Product inquiry | Predicted: Cancellation request
Actual: Technical issue | Predicted: Refund request
Actual: Cancellation request | Predicted: Technical issue
Actual: Billing inquiry | Predicted: Product inquiry
Actual: Billing inquiry | Predicted: Refund request
Actual: Billing inquiry | Predicted: Cancellation request
Actual: Cancellation request | Predicted: Billing inquiry
Actual: Billing inquiry | Predicted: Technical issue
Actual: Refund request | Predicted: Cancellation request
Actual: Refund request | Predicted: Billing inquiry
Actual: Cancellation request | Predicted: Technical issue
Actual: Cancellation request | Predicted: Cancellation request
Actual: Billing inquiry | Predicted: Product inquiry
Actual: Cancellation request | Predicted: Technical issue
Actual: Technical issue | Predicted: Technical issue
Actual: Technical issue | Predicted: Product inquiry
Actual: Billing inquiry | Predicted: Cancellation request
Actual: Product inquiry | Predicted: Product inquiry
Actual: Refund request | Predicted: Billing inquiry

In [134]:
print(df.columns.tolist())

['Ticket ID', 'Customer Name', 'Customer Email', 'Customer Age', 'Customer Gender', 'Product Purchased', 'Date of Purchase', 'Ticket Type', 'Ticket Subject', 'Ticket Description', 'Ticket Status', 'Resolution', 'Ticket Priority', 'Ticket Channel', 'First Response Time', 'Time to Resolution', 'Customer Satisfaction Rating', 'text', 'clean_text']

In [135]:
print([c for c in df.columns if "Ticket" in c])

['Ticket ID', 'Ticket Type', 'Ticket Subject', 'Ticket Description', 'Ticket Status', 'Ticket Priority', 'Ticket Channel']

In [136]:
# FINAL CLEAN TRAINING PIPELINE
# Uses Ticket Subject + cleaned Ticket Description

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
import joblib
import os

# 1. Combine subject and cleaned description
clean_df["model_text"] = (
    clean_df["Ticket Subject"].fillna("") + " " +
    clean_df["clean_text"].fillna("")
)

# 2. Define features and labels
X = clean_df["model_text"]
y = clean_df["Ticket Type"]

# 3. Fresh train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# 4. TF-IDF
final_vectorizer = TfidfVectorizer(
    ngram_range=(1, 2),
    min_df=2,
    max_df=0.95,
    sublinear_tf=True
)

X_train_tfidf = final_vectorizer.fit_transform(X_train)
X_test_tfidf = final_vectorizer.transform(X_test)

# 5. Train Logistic Regression
final_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

final_model.fit(X_train_tfidf, y_train)

# 6. Evaluate
y_pred = final_model.predict(X_test_tfidf)

final_accuracy = accuracy_score(y_test, y_pred)

print("FINAL MODEL RESULTS")
print("-------------------")
print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))
print("Features:", X_train_tfidf.shape[1])
print("Accuracy:", round(final_accuracy, 4))
print("Accuracy percentage:", round(final_accuracy * 100, 2), "%")

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# 7. Save the FINAL model and vectorizer
os.makedirs("../models", exist_ok=True)

joblib.dump(final_model, "../models/logistic_model.pkl")
joblib.dump(final_vectorizer, "../models/tfidf_vectorizer.pkl")

print("\nModel and vectorizer saved successfully!")

FINAL MODEL RESULTS
-------------------
Training samples: 6432
Testing samples: 1608
Features: 13231
Accuracy: 0.1971
Accuracy percentage: 19.71 %

Classification Report:
                      precision    recall  f1-score   support

     Billing inquiry       0.18      0.16      0.17       312
Cancellation request       0.16      0.16      0.16       322
     Product inquiry       0.23      0.22      0.22       314
      Refund request       0.19      0.21      0.20       331
     Technical issue       0.23      0.24      0.23       329

            accuracy                           0.20      1608
           macro avg       0.20      0.20      0.20      1608
        weighted avg       0.20      0.20      0.20      1608


Model and vectorizer saved successfully!

In [137]:
# DATASET LABEL CONSISTENCY CHECK

# Count how many different labels each description has
description_labels = (
    clean_df.groupby("Ticket Description")["Ticket Type"]
    .nunique()
    .sort_values(ascending=False)
)

print("Total unique descriptions:", description_labels.shape[0])
print("Descriptions with multiple labels:", (description_labels > 1).sum())
print("Maximum labels for one description:", description_labels.max())

# Show examples
ambiguous_descriptions = description_labels[description_labels > 1].head(10)

print("\nExamples of descriptions with multiple labels:\n")

for description in ambiguous_descriptions.index:
    labels = clean_df.loc[
        clean_df["Ticket Description"] == description,
        "Ticket Type"
    ].unique()

    print("Description:", description[:150])
    print("Labels:", list(labels))
    print()

Total unique descriptions: 8035
Descriptions with multiple labels: 0
Maximum labels for one description: 1

Examples of descriptions with multiple labels:

In [138]:
# Check whether Ticket Subject is more informative than Ticket Description

print("Examples by ticket type:\n")

for ticket_type in clean_df["Ticket Type"].unique():
    print("\n---", ticket_type, "---")
    
    sample = clean_df[
        clean_df["Ticket Type"] == ticket_type
    ][["Ticket Subject", "Ticket Description"]].head(3)
    
    print(sample.to_string(index=False))

Examples by ticket type:


--- Technical issue ---
          Ticket Subject                                                                                                                                                                                                                                                                                 Ticket Description
           Product setup I'm having an issue with the {product_purchased}. Please assist.\n\nYour billing zip code is: 71701.\n\nWe appreciate that you have requested a website address.\n\nPlease double check your email address. I've tried troubleshooting steps mentioned in the user manual, but the issue persists.
Peripheral compatibility   I'm having an issue with the {product_purchased}. Please assist.\n\nIf you need to change an existing product.\n\nI'm having an issue with the {product_purchased}. Please assist.\n\nIf The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.
         Network problem              I'm facing a problem with my {product_purchased}. The {product_purchased} is not turning on. It was working fine until yesterday, but now it doesn't respond.\n\n1.8.3 I really I'm using the original charger that came with my {product_purchased}, but it's not charging properly.

--- Billing inquiry ---
Ticket Subject                                                                                                                                                                                                                                                                                                                               Ticket Description
Account access                                                                         I'm having an issue with the {product_purchased}. Please assist.\n\nIf you have a problem you're interested in and I'd love to see this happen, please check out the Feedback. I've already contacted customer support multiple times, but the issue remains unresolved.
     Data loss I'm having an issue with the {product_purchased}. Please assist.\n\n\nNote: The seller is not responsible for any damages arising out of the delivery of the battleground game. Please have the game in good condition and shipped to you I've noticed a sudden decrease in battery life on my {product_purchased}. It used to last much longer.
 Product setup                                                     I'm having an issue with the {product_purchased}. Please assist.\n\nProduct Name: TPUBASK3E3KQ0\n\n\nJoin Date: Oct 2007 Posts: 11,532\n\nQuote: I've recently updated the firmware of my {product_purchased}, and the issue started happening afterward. Could it be related to the update?

--- Cancellation request ---
      Ticket Subject                                                                                                                                                                                                                                                                               Ticket Description
       Payment issue   I'm facing a problem with my {product_purchased}. The {product_purchased} is not turning on. It was working fine until yesterday, but now it doesn't respond. To remove the new {product_purch I've checked for any available software updates for my {product_purchased}, but there are none.
           Data loss                   I'm having an issue with the {product_purchased}. Please assist. 1-800-799-0808.\n\nProduct Search: What's New in 2-3-4-5? Report Feedback Customer Service is your best I'm using the original charger that came with my {product_purchased}, but it's not charging properly.
Installation support I'm having an issue with the {product_purchased}. Please assist.\n\nThe email address should change to: customer@julietr.com, as there is a unique id number unique for each product.\n\nYou I've tried different settings and configurations on my {product_purchased}, but the issue persists.

--- Product inquiry ---
Ticket Subject                                                                                                                                                                                                                                                                                                                                      Ticket Description
Refund request I'm unable to access my {product_purchased} account. It keeps displaying an 'Invalid Credentials' error, even though I'm using the correct login information. How can I regain access to my account?\n\nSolution 1 I'm unable to find the option to perform the desired action in the {product_purchased}. Could you please guide me through the steps?
  Software bug                                            I'm having an issue with the {product_purchased}. Please assist.\n\n4. It is possible that we cannot find some type of text or a product name to identify someone like Mr. Brown.\n\n5. On the I've reviewed the troubleshooting steps on the official support website, but they didn't resolve the problem.
Account access                           I'm having an issue with the {product_purchased}. Please assist.\n\n- Acknowledgement: Thanks to Dan for the tip. When you purchase a new product from my store or from your local retailer, they will also provide I'm concerned about the security of my {product_purchased} and would like to ensure that my data is safe.

--- Refund request ---
Ticket Subject                                                                                                                                                                                                                                                                                                                           Ticket Description
  Battery life I'm having an issue with the {product_purchased}. Please assist. (Thanks) I will contact all my suppliers and confirm.\n\nPlease try and find out whether their inventory is currently stocked, or any other reason. I am I've performed a factory reset on my {product_purchased}, hoping it would resolve the problem, but it didn't help.
 Payment issue                            My {product_purchased} is making strange noises and not functioning properly. I suspect there might be a hardware issue. Can you please help me with this?\n\n} If we can, please send a "request" to dav The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.
  Software bug                                       I'm having an issue with the {product_purchased}. Please assist.\n\nI'm having an issue with the product_purchased}. Please assist. Customer Reviewer: My Husband was able to take an order from Apple I've checked for any available software updates for my {product_purchased}, but there are none.

In [139]:
# FINAL SANITY CHECK
# Can the model even learn the training data?

train_predictions = clean_model.predict(X_train_tfidf)

train_accuracy = accuracy_score(y_train, train_predictions)

print("Training accuracy:", train_accuracy)
print("Training accuracy percentage:", round(train_accuracy * 100, 2), "%")

ValueError: X has 13231 features, but LogisticRegression is expecting 13208 features as input.

In [140]:
print("Model expects features:", clean_model.n_features_in_)
print("Current training features:", X_train_tfidf.shape[1])
print("Current test features:", X_test_tfidf.shape[1])

Model expects features: 13208
Current training features: 13231
Current test features: 13231

In [141]:
# Use the original TF-IDF vectorizer that the clean model was trained with

X_train_clean = vectorizer.transform(X_train)
X_test_clean = vectorizer.transform(X_test)

print("Clean training features:", X_train_clean.shape)
print("Clean testing features:", X_test_clean.shape)

train_predictions = clean_model.predict(X_train_clean)
test_predictions = clean_model.predict(X_test_clean)

print("Training accuracy:", round(accuracy_score(y_train, train_predictions) * 100, 2), "%")
print("Testing accuracy:", round(accuracy_score(y_test, test_predictions) * 100, 2), "%")

Clean training features: (6432, 13208)
Clean testing features: (1608, 13208)
Training accuracy: 71.19 %
Testing accuracy: 20.15 %

In [142]:
# Check whether ticket types are distributed consistently
# between training and testing data

print("TRAINING DISTRIBUTION")
print(y_train.value_counts(normalize=True).round(3))

print("\nTESTING DISTRIBUTION")
print(y_test.value_counts(normalize=True).round(3))

print("\nTRAINING UNIQUE DESCRIPTIONS:", X_train.nunique())
print("TESTING UNIQUE DESCRIPTIONS:", X_test.nunique())

print("\nOVERLAPPING DESCRIPTIONS:",
      len(set(X_train) & set(X_test)))

TRAINING DISTRIBUTION
Ticket Type
Refund request          0.206
Technical issue         0.204
Cancellation request    0.200
Product inquiry         0.196
Billing inquiry         0.194
Name: proportion, dtype: float64

TESTING DISTRIBUTION
Ticket Type
Refund request          0.206
Technical issue         0.205
Cancellation request    0.200
Product inquiry         0.195
Billing inquiry         0.194
Name: proportion, dtype: float64

TRAINING UNIQUE DESCRIPTIONS: 6426
TESTING UNIQUE DESCRIPTIONS: 1608

OVERLAPPING DESCRIPTIONS: 5

In [143]:
# FINAL MODEL: SUBJECT + DESCRIPTION

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Combine subject and description
X_combined = (
    clean_df["Ticket Subject"].fillna("") + " " +
    clean_df["Ticket Description"].fillna("")
)

# Use the SAME train/test indices as before
X_train_combined = X_combined.loc[X_train.index]
X_test_combined = X_combined.loc[X_test.index]

# TF-IDF
final_vectorizer = TfidfVectorizer(
    ngram_range=(1, 2),
    min_df=2,
    max_df=0.95,
    sublinear_tf=True
)

X_train_final = final_vectorizer.fit_transform(X_train_combined)
X_test_final = final_vectorizer.transform(X_test_combined)

# Model
final_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

final_model.fit(X_train_final, y_train)

# Evaluate
y_pred_final = final_model.predict(X_test_final)

final_accuracy = accuracy_score(y_test, y_pred_final)

print("FINAL MODEL")
print("=" * 40)
print("Training features:", X_train_final.shape)
print("Testing features:", X_test_final.shape)
print("Accuracy:", round(final_accuracy * 100, 2), "%")
print()
print(classification_report(y_test, y_pred_final))

FINAL MODEL
========================================
Training features: (6432, 14440)
Testing features: (1608, 14440)
Accuracy: 20.58 %

                      precision    recall  f1-score   support

     Billing inquiry       0.18      0.16      0.17       312
Cancellation request       0.17      0.18      0.17       322
     Product inquiry       0.25      0.24      0.24       314
      Refund request       0.20      0.22      0.21       331
     Technical issue       0.24      0.23      0.23       329

            accuracy                           0.21      1608
           macro avg       0.21      0.21      0.21      1608
        weighted avg       0.21      0.21      0.21      1608

In [144]:
# CHECK LABEL CONSISTENCY

label_consistency = (
    clean_df.groupby("Ticket Description")["Ticket Type"]
    .nunique()
)

print("Total unique descriptions:", len(label_consistency))
print("Descriptions with multiple labels:", (label_consistency > 1).sum())
print("Maximum labels for one description:", label_consistency.max())

print("\nExamples of conflicting descriptions:")

conflicting = label_consistency[label_consistency > 1].index

print(
    clean_df[
        clean_df["Ticket Description"].isin(conflicting)
    ][["Ticket Description", "Ticket Type"]]
    .drop_duplicates()
    .head(30)
    .to_string(index=False)
)

Total unique descriptions: 8035
Descriptions with multiple labels: 0
Maximum labels for one description: 1

Examples of conflicting descriptions:
Empty DataFrame
Columns: [Ticket Description, Ticket Type]
Index: []

In [145]:
# FINAL DIAGNOSTIC - WHY IS TEST ACCURACY SO LOW?

print("TRAINING LABEL DISTRIBUTION")
print(y_train.value_counts())

print("\nTESTING LABEL DISTRIBUTION")
print(y_test.value_counts())

print("\n-----------------------------")
print("PREDICTION DISTRIBUTION")
print(pd.Series(y_pred_clean).value_counts())

print("\n-----------------------------")
print("TRAIN/TEST TEXT OVERLAP")
print("Overlapping descriptions:",
      len(set(X_train) & set(X_test)))

print("\n-----------------------------")
print("SAMPLE TRAINING DATA")
print(pd.DataFrame({
    "text": X_train[:10],
    "label": y_train[:10]
}).to_string(index=False))

print("\n-----------------------------")
print("SAMPLE TEST DATA")
print(pd.DataFrame({
    "text": X_test[:10],
    "label": y_test[:10],
    "prediction": y_pred_clean[:10]
}).to_string(index=False))

TRAINING LABEL DISTRIBUTION
Ticket Type
Refund request          1323
Technical issue         1315
Cancellation request    1286
Product inquiry         1258
Billing inquiry         1250
Name: count, dtype: int64

TESTING LABEL DISTRIBUTION
Ticket Type
Refund request          331
Technical issue         329
Cancellation request    322
Product inquiry         314
Billing inquiry         312
Name: count, dtype: int64

-----------------------------
PREDICTION DISTRIBUTION
Refund request          373
Technical issue         346
Cancellation request    311
Product inquiry         296
Billing inquiry         282
Name: count, dtype: int64

-----------------------------
TRAIN/TEST TEXT OVERLAP
Overlapping descriptions: 5

-----------------------------
SAMPLE TRAINING DATA
                                                                                                                                                                                                                                                       text                label
                                                             Data loss data loss an with the this link is being used in place of the last option productcode e e c d experiencing this on multiple devices of the same model so it seems to be a widespread       Refund request
                                                                                                                Display issue display an with the if you have any questions ask i assistance as soon as possible because affecting my work and productivity      Billing inquiry
                                       Peripheral compatibility peripheral compatibility an with the for more information you should visit https android com en us htm htm a apk a peculiar error message popping up on my screen it says what does it mean      Technical issue
                                                                                                        Payment issue payment an with the an with the an with the product purch i assistance as soon as possible because affecting my work and productivity      Product inquiry
Installation support installation an with the for more information for the new product see the description button in your app app form this form has a separate section for the i assistance as soon as possible because affecting my work and productivity       Refund request
     Peripheral compatibility peripheral compatibility a software bug in the app causing data loss and unexpected errors how can i resolve this a software bug in the followed online tutorials and community forums to troubleshoot the but no luck so far Cancellation request
                                                                          Installation support installation an with the include u include u import this will be the first set of functions that already contacted multiple times but the remains unresolved      Product inquiry
                            Account access account access an with the received it boutiqueed by a friend but i have to tell you guys what can you have an with the democrat reviewed the troubleshooting steps on the official website but they resolve the Cancellation request
                                                                                                                  Account access account access an with the h id id purchasedat i assistance as soon as possible because affecting my work and productivity      Technical issue
        Payment issue payment an with the like to this again the product was sold to me at the store and has now been shipped to my house i haven t been back unable to find the option to perform the desired action in the you guide me through the steps       Refund request

-----------------------------
SAMPLE TEST DATA
                                                                                                                                                                                                                                                                                                                         text                label           prediction
             Payment issue payment recently set up my but it fails to connect to any available networks what steps should i take to troubleshoot this the following procedure explains the troubleshooting steps available through an online tool that the occurs consistently when i a specific feature or application on my      Technical issue      Technical issue
                                                                                                                                                                                Payment issue payment an with the note with product info allow days for delivery different settings and configurations on my but the persists      Product inquiry Cancellation request
                                                                   Cancellation request cancellation request an with the always loved this you it happen you it you re doing it right this is a place dedicated to all the other things not sure if this is specific to my device or if others have reported similar problems      Technical issue       Refund request
                                                                                          Battery life battery life an with the if you have already a product and have a link the product will be available but the link has not been marked as and the link does already contacted multiple times but the remains unresolved Cancellation request      Technical issue
                                                                                            Cancellation request cancellation request an with the in this case i have to restart my computer for it seems that if you to activate the device it be concerned about the security of my and like to ensure that my data is safe      Billing inquiry      Product inquiry
                                                                Display issue display accidentally deleted important data from my is there any way to recover the deleted files i them urgently contact size size size size this started occurring after the recent software update i haven t any other changes to the device      Billing inquiry       Refund request
Peripheral compatibility peripheral compatibility my is making strange noises and not functioning properly i suspect there might be a hardware can you me with this if you are looking for the same level of functionality this unable to find the option to perform the desired action in the you guide me through the steps      Billing inquiry Cancellation request
                                     Installation support installation an with the if not contact me note that this product is not recommended for pregnant women whose pregnancies are likely to occur at or between the ages of weeks followed online tutorials and community forums to troubleshoot the but no luck so far Cancellation request      Billing inquiry
                                                                                            Payment issue payment an with the what are the issues i have with this new product what you suggestnfl teams do to address this this new release is i rely heavily on my for my daily tasks and this is hindering my productivity      Billing inquiry      Technical issue
                                                          Installation support installation an with the product name description description us find the product you are looking for product description description description no this is not a i assistance as soon as possible because affecting my work and productivity       Refund request Cancellation request

In [146]:
print("TRAIN INDEX SAMPLE:")
print(X_train.index[:10].tolist())
print(y_train.index[:10].tolist())

print("\nTEST INDEX SAMPLE:")
print(X_test.index[:10].tolist())
print(y_test.index[:10].tolist())

print("\nINDEX ALIGNMENT:")
print("Train X/Y aligned:", X_train.index.equals(y_train.index))
print("Test X/Y aligned:", X_test.index.equals(y_test.index))

print("\nSAMPLE TRAIN PAIRS:")
for i in range(5):
    print("TEXT:", X_train.iloc[i][:100])
    print("LABEL:", y_train.iloc[i])
    print()

print("\nSAMPLE TEST PAIRS:")
for i in range(5):
    print("TEXT:", X_test.iloc[i][:100])
    print("ACTUAL:", y_test.iloc[i])
    print("PREDICTED:", y_pred_clean[i])
    print()

TRAIN INDEX SAMPLE:
[4664, 3681, 149, 6957, 3990, 1791, 2943, 7251, 6868, 2538]
[4664, 3681, 149, 6957, 3990, 1791, 2943, 7251, 6868, 2538]

TEST INDEX SAMPLE:
[6980, 293, 5817, 5212, 6207, 899, 5326, 3063, 5796, 3230]
[6980, 293, 5817, 5212, 6207, 899, 5326, 3063, 5796, 3230]

INDEX ALIGNMENT:
Train X/Y aligned: True
Test X/Y aligned: True

SAMPLE TRAIN PAIRS:
TEXT: Data loss data loss an with the this link is being used in place of the last option productcode e e
LABEL: Refund request

TEXT: Display issue display an with the if you have any questions ask i assistance as soon as possible bec
LABEL: Billing inquiry

TEXT: Peripheral compatibility peripheral compatibility an with the for more information you should visit
LABEL: Technical issue

TEXT: Payment issue payment an with the an with the an with the product purch i assistance as soon as poss
LABEL: Product inquiry

TEXT: Installation support installation an with the for more information for the new product see the descr
LABEL: Refund request


SAMPLE TEST PAIRS:
TEXT: Payment issue payment recently set up my but it fails to connect to any available networks what step
ACTUAL: Technical issue
PREDICTED: Technical issue

TEXT: Payment issue payment an with the note with product info allow days for delivery different settings
ACTUAL: Product inquiry
PREDICTED: Cancellation request

TEXT: Cancellation request cancellation request an with the always loved this you it happen you it you re
ACTUAL: Technical issue
PREDICTED: Refund request

TEXT: Battery life battery life an with the if you have already a product and have a link the product will
ACTUAL: Cancellation request
PREDICTED: Technical issue

TEXT: Cancellation request cancellation request an with the in this case i have to restart my computer for
ACTUAL: Billing inquiry
PREDICTED: Product inquiry

In [149]:
# FINAL MODEL INPUT — CLEAN DATA ONLY

clean_df["model_text"] = (
    clean_df["Ticket Subject"].fillna("") + " " +
    clean_df["Ticket Description"].fillna("")
)

X = clean_df["model_text"]
y = clean_df["Ticket Type"]

print("Model input created successfully.")
print("Total clean samples:", len(X))
print("\nExample:")
print(X.iloc[0])
print("\nLabel:", y.iloc[0])

Model input created successfully.
Total clean samples: 8040

Example:
Product setup I'm having an issue with the {product_purchased}. Please assist.

Your billing zip code is: 71701.

We appreciate that you have requested a website address.

Please double check your email address. I've tried troubleshooting steps mentioned in the user manual, but the issue persists.

Label: Technical issue

In [ ]:
# FINAL MODEL — SUBJECT + DESCRIPTION

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
import joblib

# Split clean data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

# TF-IDF
final_vectorizer = TfidfVectorizer(
    ngram_range=(1, 2),
    min_df=2,
    max_df=0.95,
    sublinear_tf=True
)

X_train_tfidf = final_vectorizer.fit_transform(X_train)
X_test_tfidf = final_vectorizer.transform(X_test)

# Train model
final_model = LogisticRegression(
    max_iter=2000,
    random_state=42
)

final_model.fit(X_train_tfidf, y_train)

# Evaluate
y_pred_final = final_model.predict(X_test_tfidf)

final_accuracy = accuracy_score(y_test, y_pred_final)

print("FINAL MODEL")
print("=" * 40)
print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))
print("Features:", X_train_tfidf.shape[1])
print("Accuracy:", round(final_accuracy * 100, 2), "%")
print()
print(classification_report(y_test, y_pred_final))



# Save model + vectorizer
from pathlib import Path

BASE_DIR = Path.cwd().parent

joblib.dump(
    final_model,
    BASE_DIR / "models" / "logistic_model.pkl"
)

joblib.dump(
    final_vectorizer,
    BASE_DIR / "models" / "tfidf_vectorizer.pkl"
)

print("Model and vectorizer saved successfully!")

FINAL MODEL
========================================
Training samples: 6432
Testing samples: 1608
Features: 14440
Accuracy: 20.58 %

                      precision    recall  f1-score   support

     Billing inquiry       0.18      0.16      0.17       312
Cancellation request       0.17      0.18      0.17       322
     Product inquiry       0.25      0.24      0.24       314
      Refund request       0.20      0.22      0.21       331
     Technical issue       0.24      0.23      0.23       329

            accuracy                           0.21      1608
           macro avg       0.21      0.21      0.21      1608
        weighted avg       0.21      0.21      0.21      1608

NameError: name 'BASE_DIR' is not defined

In [151]:
from pathlib import Path
import joblib

BASE_DIR = Path.cwd().parent

joblib.dump(
    final_model,
    BASE_DIR / "models" / "logistic_model.pkl"
)

joblib.dump(
    final_vectorizer,
    BASE_DIR / "models" / "tfidf_vectorizer.pkl"
)

print("Model and vectorizer saved successfully!")

Model and vectorizer saved successfully!